<?xml version="1.0" encoding="utf-8"?><Database Class="AuthorizationDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="Resource" Member="Resources">
    <Type Name="Resource">
      <Column Name="Id" Type="System.Int32" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Uri" Type="System.String" CanBeNull="false" />
      <Column Name="Description" Type="System.String" CanBeNull="false" />
      <Association Name="Resource_RoleResourceAction" Member="RoleResourceActions" ThisKey="Id" OtherKey="ResourceId" Type="RoleResourceAction" />
    </Type>
  </Table>
  <Table Name="RoleResourceAction" Member="RoleResourceActions">
    <Type Name="RoleResourceAction">
      <Column Name="Id" Type="System.Int32" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Int32" CanBeNull="false" />
      <Column Name="ResourceId" Type="System.Int32" CanBeNull="false" />
      <Column Name="AllowedMethods" Type="System.String" CanBeNull="false" />
      <Association Name="Resource_RoleResourceAction" Member="Resource" ThisKey="ResourceId" OtherKey="Id" Type="Resource" IsForeignKey="true" />
      <Association Name="Role_RoleResourceAction" Member="Role" ThisKey="RoleId" OtherKey="Id" Type="Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Role" Member="Roles">
    <Type Name="Role">
      <Column Name="Id" Type="System.Int32" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" CanBeNull="false" />
      <Column Name="Description" Type="System.String" CanBeNull="false" />
      <Association Name="Role_RoleResourceAction" Member="RoleResourceActions" ThisKey="Id" OtherKey="RoleId" Type="RoleResourceAction" />
      <Association Name="Role_UserRole" Member="UserRoles" ThisKey="Id" OtherKey="RoleId" Type="UserRole" />
    </Type>
  </Table>
  <Table Name="AppAuthorization" Member="AppAuthorizations">
    <Type Name="AppAuthorization">
      <Column Name="Id" Type="System.Int32" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AppId" Type="System.Int32" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" CanBeNull="false" />
      <Column Name="Scope" Type="System.String" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" CanBeNull="false" />
      <Column Name="AuthTokenExpiration" Storage="_Expiration" Type="System.DateTime" CanBeNull="true" />
      <Column Name="Token" Member="AuthToken" Type="System.String" CanBeNull="false" />
      <Column Name="RefreshToken" Type="System.String" CanBeNull="true" />
      <Column Name="RefreshTokenExpiration" Type="System.DateTime" CanBeNull="true" />
      <Association Name="Application_AppAuthorization" Member="Application" ThisKey="AppId" OtherKey="Id" Type="Application" IsForeignKey="true" />
      <Association Name="User_AppAuthorization" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Application" Member="Applications">
    <Type Name="Application">
      <Column Name="Id" Type="System.Int32" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AppPublicId" Type="System.String" CanBeNull="false" />
      <Column Name="AppSecret" Type="System.String" CanBeNull="false" />
      <Column Name="Name" Type="System.String" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" CanBeNull="false" />
      <Column Name="OwnerId" Type="System.Int32" CanBeNull="true" />
      <Association Name="Application_AppAuthorization" Member="AppAuthorizations" ThisKey="Id" OtherKey="AppId" Type="AppAuthorization" />
      <Association Name="User_Application" Member="User" ThisKey="OwnerId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="User" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ClaimId" Type="System.String" CanBeNull="false" />
      <Column Name="ClaimName" Type="System.String" CanBeNull="false" />
      <Association Name="User_AppAuthorization" Member="AppAuthorizations" ThisKey="Id" OtherKey="UserId" Type="AppAuthorization" />
      <Association Name="User_Application" Member="Applications" ThisKey="Id" OtherKey="OwnerId" Type="Application" />
      <Association Name="User_UserRole" Member="UserRoles" ThisKey="Id" OtherKey="UserId" Type="UserRole" />
    </Type>
  </Table>
  <Table Name="UserRole" Member="UserRoles">
    <Type Name="UserRole">
      <Column Name="Id" Type="System.Int32" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Int32" CanBeNull="false" />
      <Association Name="User_UserRole" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="Role_UserRole" Member="Role" ThisKey="RoleId" OtherKey="Id" Type="Role" IsForeignKey="true" />
    </Type>
  </Table>
</Database>